// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fshixqcrdchdokkhmsbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaGl4cWNyZGNoZG9ra2htc2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzQwMDIsImV4cCI6MjA2NDQxMDAwMn0.XJwtcEaeRRT6TyO6TXK9-lk9rKGEphgCo3-jjE22HLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});